# scrape_configs:
#   - job_name: "otel-collector"
#     scrape_interval: 10s
#     static_configs:
#       - targets: ["otel-collector:8888"]
#   - job_name: "tempo"
#     static_configs:
#       - targets: ["tempo:3200"]

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
