global:
  scrape_native_histograms: true

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 2s
    static_configs:
      - targets: ["otel-collector:8889"]
  # - job_name: "tempo"
  #   static_configs:
  #     - targets: ["tempo:3200"]

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
